- hosts: all
  tasks:
    - shell:
        cmd: |
          # TODO(pabelanger): migrate to bindep.txt
          sudo yum -y install centos-packager createrepo

    - name: Create koji centos cert
      copy:
        content: "{{ koji_centos.private_key }}"
        dest: ~/.centos.cert

    - name: Create koji centos server ca
      copy:
        content: "{{ koji_centos.server_ca_cert }}"
        dest: ~/.centos-server-ca.cert

    - name: Create koji centos upload ca
      copy:
        content: "{{ koji_centos.server_ca_cert }}"
        dest: ~/.centos-upload-ca.cert

    - shell:
        cmd: "WORKSPACE={{ ansible_user_dir }} ./pkg-export.sh cloud7-openstack-{{ zuul.branch|replace('-rdo', '') }}-el7 cbs"
        chdir: "{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}"
      environment: '{{ zuul | zuul_legacy_vars }}'
