---
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
log: true
platforms:
  - name: instance
provisioner:
  name: ansible
  verbose: vv
scenario:
  test_sequence:
    - lint
    - syntax
    - converge
    - verify
