---
- hosts: all
  tasks:
    - name: Create TripleO Gerrit SSH private key from secret
      copy:
        content: "{{ tripleo_gerrit_ssh_key.ssh_private_key }}"
        dest: "{{ tripleo_gerrit_key_path }}"
        mode: 0600
    - name: Create openstack config dir
      file:
        path: ~/.config/openstack/
        state: directory
    - name: Generate clouds config with ovb-test credentials
      template:
        src: ovb-test.clouds.yaml.j2
        dest: ~/.config/openstack/clouds.yaml
        mode: 0600
