---
- hosts: all
  become: true
  tasks:

    - name: Install container engine
      package:
        name: podman

    - name: Run role
      include_role:
        name: update-reproducer-zuul-images
      vars:
        container_command: podman
