---
- hosts: all
  roles:
    - role: ovb-manage-stack
      ovb_manage_stack_mode: delete
      ci_config_repo: "{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/config'].src_dir }}"
      workspace: "{{ ansible_user_dir }}/workspace"
