---
- hosts: all
  vars:
    ci_config_repo: "{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/config'].src_dir }}"
    workspace: "{{ ansible_user_dir }}/workspace"
  tasks:

    - name: Create OVB environment
      include_role:
        name: ovb-manage
      vars:
        ovb_manage_stack_mode: create
        ovb_working_dir: "{{ workspace }}/ovb"
        logs_dir: "{{ workspace }}/logs"
