jobs:
  - name: ^gate-weirdo-dlrn-master-.*$
    voting: false
    branch: ^rpm-master$

# Templates that provide optimal coverage for a project
# Packstack testing matrix:
# https://github.com/openstack/packstack#packstack-integration-tests
# Puppet testing matrix:
# https://github.com/openstack/puppet-openstack-integration#description
project-templates:
  - name: weirdo-dlrn-master-aodh
    check:
      - DLRN-rpmbuild:
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario001
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-ceilometer
    check:
      - DLRN-rpmbuild:
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario001
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-cinder
    check:
      - DLRN-rpmbuild:
        # iscsi/lvm backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # barbican encrypted volumes
        - gate-weirdo-dlrn-master-puppet-scenario002
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario002

  - name: weirdo-dlrn-master-glance
    check:
      - DLRN-rpmbuild:
        # file backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # swift backend
        - gate-weirdo-dlrn-master-puppet-scenario002
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario002

  - name: weirdo-dlrn-master-gnocchi
    check:
      - DLRN-rpmbuild:
        # file backend
        - gate-weirdo-dlrn-master-packstack-scenario003
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-heat
    check:
      - DLRN-rpmbuild:
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario003
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-neutron
    check:
      - DLRN-rpmbuild:
        # ipv4/ovs backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # ipv6/ovs backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # ipv6/linuxbridge backend
        - gate-weirdo-dlrn-master-puppet-scenario003
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-nova
    check:
      - DLRN-rpmbuild:
        # on-disk ephemeral
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd ephemeral
        - gate-weirdo-dlrn-master-puppet-scenario001
    gate:
      - DLRN-rpmbuild
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
projects:
  - name: openstack/aodh-distgit
    template:
      - name: weirdo-dlrn-master-aodh

  - name: openstack/aodhclient-distgit
    template:
      - name: weirdo-dlrn-master-aodh

  - name: openstack/barbican-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: openstack/barbicanclient-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: openstack/ceilometer-distgit
    template:
      - name: weirdo-dlrn-master-ceilometer

  - name: openstack/ceilometerclient-distgit
    template:
      - name: weirdo-dlrn-master-ceilometer

  - name: openstack/ceilometermiddleware-distgit
    template:
      - name: weirdo-dlrn-master-ceilometer

  - name: openstack/cinder-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: openstack/cinderclient-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: openstack/glance-distgit
    template:
      - name: weirdo-dlrn-master-glance

  - name: openstack/glanceclient-distgit
    template:
      - name: weirdo-dlrn-master-glance

  - name: openstack/glance_store-distgit
    template:
      - name: weirdo-dlrn-master-glance

  - name: openstack/gnocchi-distgit
    template:
      - name: weirdo-dlrn-master-gnocchi

  - name: openstack/gnocchiclient-distgit
    template:
      - name: weirdo-dlrn-master-gnocchi

  - name: openstack/heat-distgit
    template:
      - name: weirdo-dlrn-master-heat

  - name: openstack/heatclient-distgit
    template:
      - name: weirdo-dlrn-master-heat

  - name: openstack/heat-templates-distgit
    template:
      - name: weirdo-dlrn-master-heat

  - name: openstack/neutron-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutronclient-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutron-lib-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutron-fwaas-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutron-lbaas-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutron-lbaas-dashboard-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/neutron-vpnaas-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: openstack/nova-distgit
    template:
      - name: weirdo-dlrn-master-nova

  - name: openstack/novaclient-distgit
    template:
      - name: weirdo-dlrn-master-nova

  - name: openstack/os-brick-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: openstack/stevedore-distgit
    template:
      - name: weirdo-dlrn-master-nova

  - name: openstack/taskflow-distgit
    template:
      - name: weirdo-dlrn-master-glance

  - name: puppet/puppet-aodh-distgit
    template:
      - name: weirdo-dlrn-master-aodh

  - name: puppet/puppet-ceilometer-distgit
    template:
      - name: weirdo-dlrn-master-ceilometer

  - name: puppet/puppet-ceph-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: puppet/puppet-cinder-distgit
    template:
      - name: weirdo-dlrn-master-cinder

  - name: puppet/puppet-glance-distgit
    template:
      - name: weirdo-dlrn-master-glance

  - name: puppet/puppet-gnocchi-distgit
    template:
      - name: weirdo-dlrn-master-gnocchi

  - name: puppet/puppet-heat-distgit
    template:
      - name: weirdo-dlrn-master-heat

  - name: puppet/puppet-neutron-distgit
    template:
      - name: weirdo-dlrn-master-neutron

  - name: puppet/puppet-nova-distgit
    template:
      - name: weirdo-dlrn-master-nova
