jobs:
  - name: ^gate-weirdo-dlrn-master-.*$
    voting: false
    branch: ^rpm-master$

project-templates:
  - name: package-distgit-integrated-jobs
    check:
      - DLRN-rpmbuild:
        - gate-weirdo-dlrn-master-packstack-scenario001
        - gate-weirdo-dlrn-master-puppet-scenario001
    gate:
      - DLRN-rpmbuild

projects:
  - name: openstack/glanceclient-distgit
    template:
      - name: package-distgit-integrated-jobs
