jobs:
  - name: ^gate-weirdo-dlrn-master-.*$
    voting: false
    branch: ^(rpm-)?master$

# Templates that provide optimal coverage for a project
# Packstack testing matrix:
# https://github.com/openstack/packstack#packstack-integration-tests
# Puppet testing matrix:
# https://github.com/openstack/puppet-openstack-integration#description
project-templates:
  - name: weirdo-dlrn-master-aodh
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario001
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-ceilometer
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario001
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-cinder
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # iscsi/lvm backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # barbican encrypted volumes
        - gate-weirdo-dlrn-master-puppet-scenario002
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario002

  - name: weirdo-dlrn-master-glance
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # file backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # swift backend
        - gate-weirdo-dlrn-master-puppet-scenario002
        # radosgw backend
        - gate-weirdo-dlrn-master-puppet-scenario004
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario002
        - experimental-weirdo-dlrn-master-puppet-scenario004

  - name: weirdo-dlrn-master-gnocchi
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # file backend
        - gate-weirdo-dlrn-master-packstack-scenario003
        # rbd backend
        - gate-weirdo-dlrn-master-puppet-scenario001
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-heat
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-packstack-scenario003
        - gate-weirdo-dlrn-master-puppet-scenario003
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario003
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-keystone
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # uuid backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # fernet backend
        - gate-weirdo-dlrn-master-puppet-scenario003
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-neutron
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # ipv4/ovs backend
        - gate-weirdo-dlrn-master-packstack-scenario001
        # ipv6/ovs backend
        - gate-weirdo-dlrn-master-puppet-scenario001
        # ipv6/linuxbridge backend
        - gate-weirdo-dlrn-master-puppet-scenario003
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-nova
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # on-disk ephemeral
        - gate-weirdo-dlrn-master-packstack-scenario001
        # rbd ephemeral
        - gate-weirdo-dlrn-master-puppet-scenario001
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario001

  - name: weirdo-dlrn-master-oslo
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # Try to get as much general/optimal coverage as possible
        # Also used for projects that do not fit any particular project tests
        - gate-weirdo-dlrn-master-packstack-scenario002
        - gate-weirdo-dlrn-master-puppet-scenario001
        - gate-weirdo-dlrn-master-puppet-scenario003
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-packstack-scenario002
        - experimental-weirdo-dlrn-master-puppet-scenario001
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-zaqar
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # zaqar with mongodb
        - gate-weirdo-dlrn-master-puppet-scenario002
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-puppet-scenario002

  - name: weirdo-dlrn-master-horizon
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        # scenario003 includes horizon
        - gate-weirdo-dlrn-master-puppet-scenario003
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-puppet-scenario003

  - name: weirdo-dlrn-master-watcher
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-puppet-scenario004
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-puppet-scenario004

  - name: weirdo-dlrn-master-networking-bgpvpn
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-puppet-scenario004
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-puppet-scenario004

  - name: weirdo-dlrn-master-barbican
    check:
      - DLRN-rpmbuild:
        - gate-rpmlint
        - DLRN-build-tripleo
        - gate-weirdo-dlrn-master-puppet-scenario002
      - DLRN-rpmbuild-fedora
      - newton-distgit-cbs-validate
      - ocata-distgit-cbs-validate
      - pike-distgit-cbs-validate
      - queens-distgit-cbs-validate
    gate:
      - DLRN-rpmbuild
      - ocata-distgit-cbs-final-build
      - pike-distgit-cbs-final-build
      - queens-distgit-cbs-final-build
    experimental:
      - DLRN-rpmbuild:
        - experimental-weirdo-dlrn-master-puppet-scenario002

projects: []
