jobs:
- branch: ^master$
  name: ^delorean-ci$
projects:
- check:
  - tox-validate
  name: diskimage-builder
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: diskimage-builder-distgit
- check:
  - tox-validate
  name: heat-templates
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: heat-templates-distgit
- check:
  - pkg-validate
  - delorean-ci
  name: horizon-distgit
- check:
  - pkg-validate
  - delorean-ci
  name: tempest-distgit
- check:
  - pkg-validate
  - delorean-ci
  name: tripleo-incubator-distgit
- check:
  - tox-validate
  name: nova
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: nova-distgit
- check:
  - tox-validate
  name: glance
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: glance-distgit
- check:
  - tox-validate
  name: ceilometer
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ceilometer-distgit
- check:
  - tox-validate
  name: gnocchi
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: gnocchi-distgit
- check:
  - tox-validate
  name: aodh
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: aodh-distgit
- check:
  - tox-validate
  name: heat
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: heat-distgit
- check:
  - tox-validate
  name: cinder
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: cinder-distgit
- check:
  - tox-validate
  name: ironic
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironic-distgit
- check:
  - tox-validate
  name: neutron
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: neutron-distgit
- check:
  - tox-validate
  name: neutron-fwaas
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: neutron-fwaas-distgit
- check:
  - tox-validate
  name: neutron-lbaas
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: neutron-lbaas-distgit
- check:
  - tox-validate
  name: neutron-vpnaas
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: neutron-vpnaas-distgit
- check:
  - tox-validate
  name: designate
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: designate-distgit
- check:
  - tox-validate
  name: sahara
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: sahara-distgit
- check:
  - tox-validate
  name: trove
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: trove-distgit
- check:
  - tox-validate
  name: tripleo-heat-templates
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: tripleo-heat-templates-distgit
- check:
  - tox-validate
  name: tripleo-image-elements
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: tripleo-image-elements-distgit
- check:
  - tox-validate
  name: instack
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: instack-distgit
- check:
  - tox-validate
  name: manila
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: manila-distgit
- check:
  - tox-validate
  name: ironic-inspector
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironic-inspector-distgit
- check:
  - tox-validate
  name: barbican
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: barbican-distgit
- check:
  - tox-validate
  name: ec2-api
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ec2-api-distgit
- check:
  - tox-validate
  name: tripleo-puppet-elements
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: tripleo-puppet-elements-distgit
- check:
  - tox-validate
  name: rally
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: rally-distgit
- check:
  - tox-validate
  name: keystoneclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: keystoneclient-distgit
- check:
  - tox-validate
  name: glanceclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: glanceclient-distgit
- check:
  - tox-validate
  name: novaclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: novaclient-distgit
- check:
  - tox-validate
  name: swiftclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: swiftclient-distgit
- check:
  - tox-validate
  name: ceilometerclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ceilometerclient-distgit
- check:
  - tox-validate
  name: heatclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: heatclient-distgit
- check:
  - tox-validate
  name: cinderclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: cinderclient-distgit
- check:
  - tox-validate
  name: ironicclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironicclient-distgit
- check:
  - tox-validate
  name: neutronclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: neutronclient-distgit
- check:
  - tox-validate
  name: saharaclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: saharaclient-distgit
- check:
  - tox-validate
  name: troveclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: troveclient-distgit
- check:
  - tox-validate
  name: designateclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: designateclient-distgit
- check:
  - tox-validate
  name: manilaclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: manilaclient-distgit
- check:
  - tox-validate
  name: barbicanclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: barbicanclient-distgit
- check:
  - tox-validate
  name: keystonemiddleware
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: keystonemiddleware-distgit
- check:
  - tox-validate
  name: ceilometermiddleware
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ceilometermiddleware-distgit
- check:
  - tox-validate
  name: openstackclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: openstackclient-distgit
- check:
  - tox-validate
  name: ironic-inspector-client
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironic-inspector-client-distgit
- check:
  - tox-validate
  name: zaqarclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: zaqarclient-distgit
- check:
  - tox-validate
  name: magnumclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: magnumclient-distgit
- check:
  - tox-validate
  name: os-client-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-client-config-distgit
- check:
  - tox-validate
  name: mox3
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: mox3-distgit
- check:
  - tox-validate
  name: oslotest
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslotest-distgit
- check:
  - tox-validate
  name: oslo-sphinx
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-sphinx-distgit
- check:
  - tox-validate
  name: oslo-i18n
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-i18n-distgit
- check:
  - tox-validate
  name: oslo-messaging
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-messaging-distgit
- check:
  - tox-validate
  name: oslo-cache
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-cache-distgit
- check:
  - tox-validate
  name: oslo-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-config-distgit
- check:
  - tox-validate
  name: oslo-concurrency
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-concurrency-distgit
- check:
  - tox-validate
  name: oslo-rootwrap
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-rootwrap-distgit
- check:
  - tox-validate
  name: oslo-serialization
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-serialization-distgit
- check:
  - tox-validate
  name: oslo-middleware
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-middleware-distgit
- check:
  - tox-validate
  name: oslo-db
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-db-distgit
- check:
  - tox-validate
  name: oslo-utils
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-utils-distgit
- check:
  - tox-validate
  name: oslo-vmware
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-vmware-distgit
- check:
  - tox-validate
  name: oslo-context
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-context-distgit
- check:
  - tox-validate
  name: oslo-log
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-log-distgit
- check:
  - tox-validate
  name: oslo-policy
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-policy-distgit
- check:
  - tox-validate
  name: oslo-versionedobjects
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-versionedobjects-distgit
- check:
  - tox-validate
  name: oslo-service
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-service-distgit
- check:
  - tox-validate
  name: oslo-reports
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: oslo-reports-distgit
- check:
  - tox-validate
  name: stevedore
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: stevedore-distgit
- check:
  - tox-validate
  name: castellan
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: castellan-distgit
- check:
  - tox-validate
  name: taskflow
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: taskflow-distgit
- check:
  - tox-validate
  name: pycadf
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: pycadf-distgit
- check:
  - tox-validate
  name: debtcollector
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: debtcollector-distgit
- check:
  - tox-validate
  name: automaton
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: automaton-distgit
- check:
  - tox-validate
  name: cliff
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: cliff-distgit
- check:
  - tox-validate
  name: futurist
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: futurist-distgit
- check:
  - tox-validate
  name: hacking
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: hacking-distgit
- check:
  - tox-validate
  name: appdirs
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: appdirs-distgit
- check:
  - tox-validate
  name: os-brick
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-brick-distgit
- check:
  - tox-validate
  name: unicodecsv
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: unicodecsv-distgit
- check:
  - tox-validate
  name: hardware
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: hardware-distgit
- check:
  - tox-validate
  name: keystoneauth1
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: keystoneauth1-distgit
- check:
  - tox-validate
  name: tempest-lib
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: tempest-lib-distgit
- check:
  - tox-validate
  name: os-testr
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-testr-distgit
- check:
  - tox-validate
  name: proliantutils
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: proliantutils-distgit
- check:
  - tox-validate
  name: requestsexceptions
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: requestsexceptions-distgit
- check:
  - tox-validate
  name: tooz
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: tooz-distgit
- check:
  - tox-validate
  name: reno
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: reno-distgit
- check:
  - tox-validate
  name: cloudkitty
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: cloudkitty-distgit
- check:
  - tox-validate
  name: keystone
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: keystone-distgit
- check:
  - tox-validate
  name: mistral
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: mistral-distgit
- check:
  - tox-validate
  name: octavia
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: octavia-distgit
- check:
  - tox-validate
  name: ironic-lib
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironic-lib-distgit
- check:
  - tox-validate
  name: os-win
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-win-distgit
- check:
  - tox-validate
  name: mistralclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: mistralclient-distgit
- check:
  - tox-validate
  name: dracclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: dracclient-distgit
- check:
  - tox-validate
  name: openstacksdk
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: openstacksdk-distgit
- check:
  - tox-validate
  name: cloudkittyclient
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: cloudkittyclient-distgit
- check:
  - tox-validate
  name: glance_store
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: glance_store-distgit
- check:
  - tox-validate
  name: swift
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: swift-distgit
- check:
  - tox-validate
  name: dib-utils
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: dib-utils-distgit
- check:
  - tox-validate
  name: os-apply-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-apply-config-distgit
- check:
  - tox-validate
  name: os-collect-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-collect-config-distgit
- check:
  - tox-validate
  name: os-net-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-net-config-distgit
- check:
  - tox-validate
  name: os-refresh-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-refresh-config-distgit
- check:
  - tox-validate
  name: os-cloud-config
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: os-cloud-config-distgit
- check:
  - tox-validate
  name: zaqar
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: zaqar-distgit
- check:
  - tox-validate
  name: ironic-python-agent
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: ironic-python-agent-distgit
- check:
  - tox-validate
  name: openstack-puppet-modules
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: openstack-puppet-modules-distgit
- check:
  - tox-validate
  name: networking-arista
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: networking-arista-distgit
- check:
  - tox-validate
  name: osprofiler
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: osprofiler-distgit
- check:
  - tox-validate
  name: pysaml2
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: pysaml2-distgit
- check:
  - tox-validate
  name: networking-cisco
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: networking-cisco-distgit
- check:
  - tox-validate
  name: vmware-nsx
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: vmware-nsx-distgit
- check:
  - tox-validate
  name: networking-mlnx
  periodic:
  - upstream-update
- check:
  - pkg-validate
  - delorean-ci
  name: networking-mlnx-distgit
