---
registry_server: docker.io
container_namespace: rdoci
original_namespace: zuul
original_tag: latest
push_tag: stable
container_command: podman
containers:
  - zuul
  - zuul-scheduler
  - zuul-web
  - zuul-executor
  - zuul-merger
  - zuul-fingergw
  - nodepool-launcher
