---
- name: Find out UUID of instance
  shell: curl http://169.254.169.254/openstack/latest/meta_data.json 2>/dev/null
  register: js
  no_log: true

- name: Set UUID of undercloud
  set_fact:
    undercloud_uuid: "{{ js.stdout | from_json | json_query('uuid') }}"
