---
- name: Find out UUID of instance
  shell: >-
    curl http://169.254.169.254/openstack/latest/meta_data.json 2>/dev/null |
    python -c 'import json, sys; print json.load(sys.stdin)["uuid"]'
  register: js

- name: Set UUID of undercloud
  set_fact:
    undercloud_uuid: "{{ js.stdout }}"
